{"name": "test_process_excel_urls", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'Configuration' has no attribute 'load_config'. Did you mean: 'get_config'?", "trace": "self = <url_processor_project.tests.test_url_processor.TestURLProcessor object at 0x000001D28FA173E0>\n\n    @pytest.fixture(scope=\"class\")\n    def excel_urls(self):\n        \"\"\"Fixture to read URLs from Excel file\"\"\"\n>       config = Configuration.get_config()\n\ntest_url_processor.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @staticmethod\n    def get_config():\n        \"\"\"Get combined configuration with defaults\"\"\"\n        project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))\n>       custom_config = Configuration.load_config()\nE       AttributeError: type object 'Configuration' has no attribute 'load_config'. Did you mean: 'get_config'?\n\n..\\utils\\config_handler.py:32: AttributeError"}, "description": "Test processing URLs from Excel file with error detection", "start": 1730999415726, "stop": 1730999415726, "uuid": "6fd7c890-d614-4cdd-b1d3-a675ea99a30d", "historyId": "be5f01bbfe467b80211c2ce078a6b793", "testCaseId": "be5f01bbfe467b80211c2ce078a6b793", "fullName": "tests.test_url_processor.TestURLProcessor#test_process_excel_urls", "labels": [{"name": "story", "value": "Process URLs from Excel with Error Detection"}, {"name": "feature", "value": "URL Validation and Error Detection"}, {"name": "epic", "value": "URL Processing"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_url_processor"}, {"name": "subSuite", "value": "TestURLProcessor"}, {"name": "host", "value": "DESKTOP-BL4C2NE"}, {"name": "thread", "value": "36692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_url_processor"}]}